-- Insert sample products into the database
-- Corrected to match the actual products table schema

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('SanDisk Cruzer Blade 64GB USB 2.0 Flash Drive SDCZ50-064G', '<p>The SanDisk Cruzer Blade 64GB USB 2.0 Flash Drive offers compact and portable storage for everyday use. Ideal for transferring photos, videos, and documents, it provides reliable performance for home, school, or office needs.</p><p><strong>Key Features:</strong></p><ul><li>64GB storage capacity</li><li>USB 2.0 interface for compatibility</li><li>Up to 20MB/s read speed</li><li>Compact design with no cap</li><li>SanDisk SecureAccess software for password protection</li><li>Lightweight and durable</li></ul><p></p>', 'Pendrive', 'SDCZ50-064G', 900, 290, 'Pendrive', 'SanDisk', 'placeholder_image.jpg', 'SDCZ50-064G', '85235100', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('SanDisk Ultra 64GB USB 3.0 Flash Drive SDCZ48-064G', '<p>The SanDisk Ultra 64GB USB 3.0 Flash Drive combines high-speed data transfer with generous storage capacity. Ideal for quickly moving large files like HD videos and photos, it''s perfect for professionals and students.</p><p><strong>Key Features:</strong></p><ul><li>64GB storage capacity</li><li>Up to 130MB/s read speed</li><li>USB 3.0 interface (backward compatible with USB 2.0)</li><li>SanDisk SecureAccess software with 128-bit AES encryption</li><li>Retractable connector design</li><li>5-year limited warranty</li></ul><p></p>', 'Pendrive', 'SDCZ48-064G', 1150, 375, 'Pendrive', 'SanDisk', 'placeholder_image.jpg', 'SDCZ48-064G', '85235100', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('SanDisk Ultra Dual Drive Go 64GB USB Type-C Flash Drive SDDDC3-064G', '<p>The SanDisk Ultra Dual Drive Go 64GB USB Type-C Flash Drive offers versatile storage with dual USB Type-C and Type-A connectors, perfect for transferring files between smartphones, tablets, and computers.</p><p><strong>Key Features:</strong></p><ul><li>64GB storage capacity</li><li>Up to 150MB/s read speed</li><li>USB 3.1 Gen 1 with Type-C and Type-A connectors</li><li>Swivel design with keyring hole</li><li>SanDisk Memory Zone app for file management</li><li>5-year limited warranty</li></ul><p></p>', 'Pendrive', 'SDDDC3-064G', 1200, 475, 'Pendrive', 'SanDisk', 'placeholder_image.jpg', 'SDDDC3-064G', '85235100', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('SanDisk Ultra Dual Drive Go 128GB USB Type-C Flash Drive SDDDC3-128G', '<p>The SanDisk Ultra Dual Drive Go 128GB USB Type-C Flash Drive provides versatile storage with dual USB Type-C and Type-A connectors, ideal for transferring large files between smartphones, tablets, and computers.</p><p><strong>Key Features:</strong></p><ul><li>128GB storage capacity</li><li>Up to 150MB/s read speed</li><li>USB 3.1 Gen 1 with Type-C and Type-A connectors</li><li>Swivel design with keyring hole</li><li>SanDisk Memory Zone app for file management</li><li>5-year limited warranty</li></ul><p></p>', 'Pendrive', 'SDDDC3-128G', 2250, 800, 'Pendrive', 'SanDisk', 'placeholder_image.jpg', 'SDDDC3-128G', '85235100', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('SanDisk Cruzer Blade 128GB USB 2.0 Flash Drive SDCZ50-128G', '<p>The SanDisk Cruzer Blade 128GB USB 2.0 Flash Drive offers compact and reliable storage for transferring large files like videos, music, and documents. Perfect for students, professionals, and casual users.</p><p><strong>Key Features:</strong></p><ul><li>128GB storage capacity</li><li>USB 2.0 interface for compatibility</li><li>Up to 20MB/s read speed</li><li>Compact capless design</li><li>SanDisk SecureAccess software for password protection</li><li>Lightweight and portable</li></ul><p></p>', 'Pendrive', 'SDCZ50-128G', 2200, 545, 'Pendrive', 'SanDisk', 'placeholder_image.jpg', 'SDCZ50-128G', '85235100', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('SanDisk Ultra 256GB USB 3.0 Flash Drive SDCZ48-256G', '<p>The SanDisk Ultra 256GB USB 3.0 Flash Drive offers high-capacity storage and fast data transfer speeds, perfect for large files like 4K videos and backups. Ideal for professionals and content creators.</p><p><strong>Key Features:</strong></p><ul><li>256GB storage capacity</li><li>Up to 130MB/s read speed</li><li>USB 3.0 interface (backward compatible with USB 2.0)</li><li>SanDisk SecureAccess software with 128-bit AES encryption</li><li>Retractable connector design</li><li>5-year limited warranty</li></ul><p></p>', 'Pendrive', 'SDCZ48-256G', 2900, 1295, 'Pendrive', 'SanDisk', 'placeholder_image.jpg', 'SDCZ48-256G', '85235100', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 128GB 2.5-Inch SATA SSD EVM25/128GB', '<p>EVM 128GB 2.5-Inch SATA SSD delivers high-speed performance for laptops and desktops, ideal for upgrading from traditional HDDs. With fast read and write speeds, it enhances boot times and application loading, perfect for everyday computing needs.</p><p><strong>Key Features:</strong></p><ul><li>128GB storage capacity</li><li>Up to 550MB/s read speed</li><li>Up to 500MB/s write speed</li><li>3D NAND technology for durability</li><li>Low power consumption</li><li>Shock resistance up to 1500G/0.5ms</li></ul><p></p>', 'Storage', 'EVM25/128GB', 2999, 695, 'Storage', 'EVM', 'placeholder_image.jpg', 'EVM25/128GB', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 128GB M.2 NVMe SSD EVMNV/128GB', '<p>EVM 128GB M.2 NVMe SSD offers ultra-fast performance for gaming, professional workloads, and system upgrades. With PCIe Gen 3x4 interface, it provides superior speed compared to SATA SSDs, ideal for compact devices.</p><p><strong>Key Features:</strong></p><ul><li>128GB storage capacity</li><li>Up to 1800MB/s read speed</li><li>Up to 1000MB/s write speed</li><li>PCIe Gen 3x4 interface</li><li>Shock resistance up to 1500G/0.5ms</li><li>Low power consumption</li></ul><p></p>', 'Storage', 'EVMNV/128GB', 3999, 850, 'Storage', 'EVM', 'placeholder_image.jpg', 'EVMNV/128GB', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 256GB 2.5-Inch SATA SSD EVM25/256GB', '<p>EVM 256GB 2.5-Inch SATA SSD provides reliable and fast storage for laptops and desktops, offering improved performance over traditional HDDs. Ideal for multitasking and general computing needs.</p><p><strong>Key Features:</strong></p><ul><li>256GB storage capacity</li><li>Up to 550MB/s read speed</li><li>Up to 500MB/s write speed</li><li>3D NAND technology for durability</li><li>Low power consumption</li><li>Shock resistance up to 1500G/0.5ms</li></ul><p></p>', 'Storage', 'EVM25/256GB', 3999, 1100, 'Storage', 'EVM', 'placeholder_image.jpg', 'EVM25/256GB', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 256GB M.2 NVMe SSD EVMNV/256GB', '<p>EVM 256GB M.2 NVMe SSD delivers high-speed performance for gaming, professional applications, and system upgrades. With PCIe Gen 3x4 interface, it offers faster data transfer compared to SATA SSDs, ideal for compact systems.</p><p><strong>Key Features:</strong></p><ul><li>256GB storage capacity</li><li>Up to 3000MB/s read speed</li><li>Up to 2000MB/s write speed</li><li>PCIe Gen 3x4 interface</li><li>Shock resistance up to 1500G/0.5ms</li><li>Low power consumption</li></ul><p></p>', 'Storage', 'EVMNV/256GB', 5999, 1250, 'Storage', 'EVM', 'placeholder_image.jpg', 'EVMNV/256GB', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 512GB 2.5-Inch SATA SSD EVM25/512GB', '<p>EVM 512GB 2.5-Inch SATA SSD offers ample storage and fast performance for laptops and desktops, ideal for professionals and gamers. It enhances system responsiveness and reduces load times compared to HDDs.</p><p><strong>Key Features:</strong></p><ul><li>512GB storage capacity</li><li>Up to 550MB/s read speed</li><li>Up to 500MB/s write speed</li><li>3D NAND technology for durability</li><li>Low power consumption</li><li>Shock resistance up to 1500G/0.5ms</li></ul><p></p>', 'Storage', 'EVM25/512GB', 7999, 2000, 'Storage', 'EVM', 'placeholder_image.jpg', 'EVM25/512GB', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 512GB M.2 NVMe SSD EVMNV/512GB', '<p>EVM 512GB M.2 NVMe SSD provides exceptional speed for gaming, content creation, and professional workloads. With PCIe Gen 3x4 interface, it delivers significantly faster performance than SATA SSDs, ideal for high-performance systems.</p><p><strong>Key Features:</strong></p><ul><li>512GB storage capacity</li><li>Up to 3200MB/s read speed</li><li>Up to 2000MB/s write speed</li><li>PCIe Gen 3x4 interface</li><li>Shock resistance up to 1500G/0.5ms</li><li>Low power consumption</li></ul><p></p>', 'Storage', 'EVMNV/512GB', 8999, 2150, 'Storage', 'EVM', 'placeholder_image.jpg', 'EVMNV/512GB', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 1TB 2.5-Inch SATA SSD EVM25/1TB', '<p>EVM 1TB 2.5-Inch SATA SSD offers large storage capacity and fast performance for laptops and desktops, ideal for professionals, gamers, and content creators. It significantly improves system speed and storage compared to HDDs.</p><p><strong>Key Features:</strong></p><ul><li>1TB storage capacity</li><li>Up to 550MB/s read speed</li><li>Up to 370MB/s write speed</li><li>3D NAND technology for durability</li><li>Low power consumption</li><li>Shock resistance up to 1500G/0.5ms</li></ul><p></p>', 'Storage', 'EVM25/1TB', 19999, 3350, 'Storage', 'EVM', 'placeholder_image.jpg', 'EVM25/1TB', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Intel Core i3-12100 Desktop Processor', '<p>The Intel Core i3-12100 is a 12th Gen Alder Lake processor designed for budget-friendly desktops, offering solid performance for gaming and productivity. With 4 performance cores and 8 threads, its ideal for entry-level PCs.</p><p><strong>Key Features:</strong></p><ul><li>4 cores, 8 threads</li><li>Up to 4.3 GHz turbo frequency</li><li>12MB L3 cache</li><li>58W TDP</li><li>Supports DDR5 4800 MT/s and DDR4 3200 MT/s</li><li>Requires discrete graphics</li></ul><p></p>', 'Processor', 'BX8071512100F', 19000, 8000, 'Processor', 'Intel', 'placeholder_image.jpg', 'BX8071512100F', '84733010', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Intel Core i5-12400F Desktop Processor', '<p>The Intel Core i5-12400F is a 12th Gen Alder Lake processor offering excellent value for gamers and multitaskers. With 6 performance cores and 12 threads, it delivers strong performance without integrated graphics, requiring a discrete GPU.</p><p><strong>Key Features:</strong></p><ul><li>6 cores, 12 threads</li><li>Up to 4.4 GHz turbo frequency</li><li>18MB L3 cache</li><li>65W TDP</li><li>Supports DDR5 4800 MT/s and DDR4 3200 MT/s</li><li>Ideal for gaming with discrete GPUs</li></ul><p></p>', 'Processor', 'BX8071512400F', 24140, 7850, 'Processor', 'Intel', 'placeholder_image.jpg', 'BX8071512400F', '84733010', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Intel Core i5-12400 Desktop Processor', '<p>The Intel Core i5-12400 is a 12th Gen Alder Lake processor with integrated UHD 730 graphics, ideal for gaming and productivity without needing a discrete GPU. It features 6 performance cores and 12 threads for robust performance.</p><p><strong>Key Features:</strong></p><ul><li>6 cores, 12 threads</li><li>Up to 4.4 GHz turbo frequency</li><li>18MB L3 cache</li><li>65W TDP</li><li>Integrated Intel UHD 730 graphics</li><li>Supports DDR5 4800 MT/s and DDR4 3200 MT/s</li></ul><p></p>', 'Processor', 'BX8071512400', 28500, 10450, 'Processor', 'Intel', 'placeholder_image.jpg', 'BX8071512400', '84733010', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM H61 Motherboard', '<p>The EVM H61 Motherboard is a budget-friendly option for 2nd and 3rd Gen Intel Core processors, ideal for basic computing and small office setups. It supports DDR3 memory and offers reliable performance for entry-level systems.</p><p><strong>Key Features:</strong></p><ul><li>Supports 2nd/3rd Gen Intel Core processors</li><li>LGA 1155 socket</li><li>Dual-channel DDR3 1600/1333 MHz support</li><li>1 PCIe x16 slot</li><li>2 SATA 3Gb/s ports</li><li>Integrated VGA output</li></ul><p></p>', 'Motherboard', 'EVM-H61', 4999, 900, 'Motherboard', 'EVM', 'placeholder_image.jpg', 'EVM-H61', '84733020', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM H81 Motherboard', '<p>The EVM H81 Motherboard supports 4th Gen Intel Core processors, offering a balance of performance and affordability for home and office PCs. It features DDR3 memory support and multiple connectivity options.</p><p><strong>Key Features:</strong></p><ul><li>Supports 4th Gen Intel Core processors</li><li>LGA 1150 socket</li><li>Dual-channel DDR3 1600/1333 MHz support</li><li>1 PCIe x16 slot</li><li>2 SATA 6Gb/s, 2 SATA 3Gb/s ports</li><li>Integrated VGA and HDMI outputs</li></ul><p></p>', 'Motherboard', 'EVM-H81', 5999, 1425, 'Motherboard', 'EVM', 'placeholder_image.jpg', 'EVM-H81', '84733020', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM H110 Motherboard', '<p>The EVM H110 Motherboard is designed for 6th and 7th Gen Intel Core processors, offering reliable performance for budget builds. It supports DDR4 memory and provides essential connectivity for small PCs.</p><p><strong>Key Features:</strong></p><ul><li>Supports 6th/7th Gen Intel Core processors</li><li>LGA 1151 socket</li><li>Dual-channel DDR4 2400/2133 MHz support</li><li>1 PCIe x16 slot</li><li>2 SATA 6Gb/s ports</li><li>Integrated VGA and HDMI outputs</li></ul><p></p>', 'Motherboard', 'EVM-H110', 12999, 2700, 'Motherboard', 'EVM', 'placeholder_image.jpg', 'EVM-H110', '84733020', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Zebronics H310 Motherboard', '<p>The Zebronics H310 Motherboard supports 8th and 9th Gen Intel Core processors, offering a budget-friendly option for compact PCs. It supports DDR4 memory and essential connectivity for home and office use.</p><p><strong>Key Features:</strong></p><ul><li>Supports 8th/9th Gen Intel Core processors</li><li>LGA 1151 socket</li><li>Dual-channel DDR4 2666/2400 MHz support</li><li>1 PCIe x16 slot</li><li>2 SATA 6Gb/s ports</li><li>Integrated VGA and HDMI outputs</li></ul><p></p>', 'Motherboard', 'ZEB-H310', 9999, 3000, 'Motherboard', 'Zebronics', 'placeholder_image.jpg', 'ZEB-H310', '84733020', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 2GB DDR2 667 RAM', '<p>EVM 2GB DDR2 667 RAM is designed for older PCs and laptops, offering reliable performance for basic computing tasks like browsing and office work. Its compatible with DDR2 motherboards.</p><p><strong>Key Features:</strong></p><ul><li>2GB capacity</li><li>667 MHz speed</li><li>DDR2 DIMM form factor</li><li>Low power consumption</li><li>Stable performance for legacy systems</li><li>Non-ECC, unbuffered</li></ul><p></p>', 'RAM', 'EVM-DDR2-2GB-667', 2999, 275, 'RAM', 'EVM', 'placeholder_image.jpg', 'EVM-DDR2-2GB-667', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 4GB DDR3 1600 RAM', '<p>EVM 4GB DDR3 1600 RAM provides reliable performance for older desktops and laptops, suitable for multitasking and light gaming. Its compatible with DDR3 motherboards for budget upgrades.</p><p><strong>Key Features:</strong></p><ul><li>4GB capacity</li><li>1600 MHz speed</li><li>DDR3 DIMM form factor</li><li>Low power consumption</li><li>Non-ECC, unbuffered</li><li>Stable performance for legacy systems</li></ul><p></p>', 'RAM', 'EVM-DDR3-4GB-1600', 3999, 450, 'RAM', 'EVM', 'placeholder_image.jpg', 'EVM-DDR3-4GB-1600', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 8GB DDR3 1600 RAM', '<p>EVM 8GB DDR3 1600 RAM offers enhanced performance for older desktops and laptops, ideal for multitasking, light gaming, and productivity tasks. Its compatible with DDR3 motherboards.</p><p><strong>Key Features:</strong></p><ul><li>8GB capacity</li><li>1600 MHz speed</li><li>DDR3 DIMM form factor</li><li>Low power consumption</li><li>Non-ECC, unbuffered</li><li>Reliable for legacy systems</li></ul><p></p>', 'RAM', 'EVM-DDR3-8GB-1600', 9999, 700, 'RAM', 'EVM', 'placeholder_image.jpg', 'EVM-DDR3-8GB-1600', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('EVM 8GB DDR4 2666 RAM', '<p>EVM 8GB DDR4 2666 RAM provides fast and reliable performance for modern desktops and laptops, suitable for gaming, multitasking, and productivity. Its compatible with DDR4 motherboards.</p><p><strong>Key Features:</strong></p><ul><li>8GB capacity</li><li>2666 MHz speed</li><li>DDR4 DIMM form factor</li><li>Low power consumption</li><li>Non-ECC, unbuffered</li><li>Enhanced system responsiveness</li></ul><p></p>', 'RAM', 'EVM-DDR4-8GB-2666', 9999, 800, 'RAM', 'EVM', 'placeholder_image.jpg', 'EVM-DDR4-8GB-2666', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Crucial 8GB DDR4 3200 RAM', '<p>Crucial 8GB DDR4 3200 RAM delivers high-speed performance for modern desktops and laptops, ideal for gaming, multitasking, and professional applications. Its compatible with DDR4 motherboards for optimal system performance.</p><p><strong>Key Features:</strong></p><ul><li>8GB capacity</li><li>3200 MHz speed</li><li>DDR4 DIMM form factor</li><li>Low power consumption</li><li>Non-ECC, unbuffered</li><li>Enhanced system responsiveness</li></ul><p></p>', 'RAM', 'CT8G4DFRA32A', 2400, 1150, 'RAM', 'Crucial', 'placeholder_image.jpg', 'CT8G4DFRA32A', '84733030', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Artis 3.0 Cabinet with SMPS', '<p>The Artis 3.0 Cabinet with SMPS is a compact ATX case with an integrated power supply, designed for budget PC builds. It offers decent airflow and space for essential components.</p><p><strong>Key Features:</strong></p><ul><li>ATX form factor support</li><li>Integrated 450W SMPS</li><li>1 x 120mm fan included</li><li>2 x 3.5 HDD bays, 2 x 2.5 SSD bays</li><li>Front USB 2.0 and audio ports</li><li>Side panel with ventilation</li></ul><p></p>', 'Cabinet with SMPS', 'ARTIS-3.0-CABSMPS', 5749, 1600, 'Cabinet', 'Artis', 'placeholder_image.jpg', 'ARTIS-3.0-CABSMPS', '85371000', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Enter 19-Inch LED Monitor', '<p>The Enter 19-Inch LED Monitor offers a compact display solution for home and office use, with a clear 1366x768 resolution and VGA connectivity. Ideal for basic computing tasks.</p><p><strong>Key Features:</strong></p><ul><li>19-inch LED display</li><li>1366x768 HD resolution</li><li>5ms response time</li><li>VGA input</li><li>Energy-efficient design</li><li>Wall-mountable</li></ul><p></p>', 'LED Monitor', 'ENTER-19LED', 12500, 1650, 'Monitor', 'Enter', 'placeholder_image.jpg', 'ENTER-19LED', '8528', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Zebronics 600VA UPS', '<p>The Zebronics 600VA UPS provides reliable power backup for desktops, routers, and small electronics, ensuring protection against power surges and outages. Ideal for home and small office use.</p><p><strong>Key Features:</strong></p><ul><li>600VA/360W capacity</li><li>Automatic voltage regulation</li><li>Up to 20 minutes backup time</li><li>2 output sockets</li><li>Overload and short-circuit protection</li><li>LED indicators</li></ul><p></p>', 'UPS', 'ZEB-UPS600VA', 3299, 1550, 'UPS', 'Zebronics', 'placeholder_image.jpg', 'ZEB-UPS600VA', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Zebronics 1100VA UPS', '<p>The Zebronics 1100VA UPS offers robust power backup for desktops, gaming consoles, and office equipment, protecting against power surges and outages. Suitable for medium-sized setups.</p><p><strong>Key Features:</strong></p><ul><li>1100VA/660W capacity</li><li>Automatic voltage regulation</li><li>Up to 30 minutes backup time</li><li>3 output sockets</li><li>Overload and short-circuit protection</li><li>LED indicators</li></ul><p></p>', 'UPS', 'ZEB-UPS1100VA', 5299, 3250, 'UPS', 'Zebronics', 'placeholder_image.jpg', 'ZEB-UPS1100VA', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Tenda F3 Wireless N300 Router', '<p>The Tenda F3 Wireless N300 Router offers reliable Wi-Fi connectivity for homes and small offices, with speeds up to 300Mbps. Its easy to set up and provides stable coverage for multiple devices.</p><p><strong>Key Features:</strong></p><ul><li>Up to 300Mbps Wi-Fi speed</li><li>3 x 5dBi external antennas</li><li>2.4 GHz frequency band</li><li>4 LAN ports, 1 WAN port</li><li>WPA/WPA2 security</li><li>Easy setup with web interface</li></ul><p></p>', 'Routers', 'TENDA-F3', 1400, 775, 'Routers', 'Tenda', 'placeholder_image.jpg', 'TENDA-F3', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('TP-Link Archer C6 AC1200 Wireless Router', '<p>The TP-Link Archer C6 AC1200 Wireless Router delivers high-speed dual-band Wi-Fi for homes and offices, with speeds up to 1200Mbps. It offers robust coverage and advanced features for multiple devices.</p><p><strong>Key Features:</strong></p><ul><li>Up to 1200Mbps (867Mbps on 5GHz, 300Mbps on 2.4GHz)</li><li>4 x 5dBi external antennas</li><li>MU-MIMO technology</li><li>4 LAN ports, 1 WAN port</li><li>WPA3 security</li><li>Easy setup with Tether app</li></ul><p></p>', 'Routers', 'ARCHER-C6', 4999, 1830, 'Routers', 'TP-Link', 'placeholder_image.jpg', 'ARCHER-C6', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('TP-Link TL-WR850N Wireless N300 Router', '<p>The TP-Link TL-WR850N Wireless N300 Router provides reliable Wi-Fi connectivity for homes and small offices, with speeds up to 300Mbps. Its easy to set up and offers stable performance.</p><p><strong>Key Features:</strong></p><ul><li>Up to 300Mbps Wi-Fi speed</li><li>2 x 5dBi external antennas</li><li>2.4 GHz frequency band</li><li>4 LAN ports, 1 WAN port</li><li>WPA/WPA2 security</li><li>Easy setup with Tether app</li></ul><p></p>', 'Routers', 'TL-WR850N', 1599, 750, 'Routers', 'TP-Link', 'placeholder_image.jpg', 'TL-WR850N', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Kaspersky Internet Security 1 User', '<p>Kaspersky Internet Security for 1 User provides comprehensive protection against viruses, malware, ransomware, and online threats. It includes real-time scanning, firewall, and safe browsing features for secure digital experiences.</p><p><strong>Key Features:</strong></p><ul><li>Protection for 1 device (1-year subscription)</li><li>Real-time antivirus and anti-malware</li><li>Firewall and anti-phishing protection</li><li>Safe browsing and privacy tools</li><li>Compatible with Windows, macOS, Android</li><li>24/7 customer support</li></ul><p></p>', 'Antivirus', 'KASP-IS-1USER', 700, 400, 'Antivirus', 'Kaspersky', 'placeholder_image.jpg', 'KASP-IS-1USER', '998434', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Quick Heal Internet Security 1 User', '<p>Quick Heal Internet Security for 1 User offers robust protection against viruses, malware, and online threats, with features like web security, email protection, and parental control for safe browsing.</p><p><strong>Key Features:</strong></p><ul><li>Protection for 1 device (1-year subscription)</li><li>Antivirus and anti-malware</li><li>Web and email security</li><li>Parental control</li><li>Compatible with Windows</li><li>24/7 customer support</li></ul><p></p>', 'Antivirus', 'QH-IS-1USER', 1409, 450, 'Antivirus', 'Quick Heal', 'placeholder_image.jpg', 'QH-IS-1USER', '998434', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Artis SMP 400C SMPS', '<p>The Artis SMP 400C SMPS is a compact 400W power supply unit designed for budget PC builds, offering stable power delivery and essential protection features for desktops.</p><p><strong>Key Features:</strong></p><ul><li>400W power output</li><li>80mm cooling fan</li><li>Overload and short-circuit protection</li><li>ATX form factor</li><li>Multiple power connectors</li><li>Energy-efficient design</li></ul><p></p>', 'SMPS', 'ARTIS-SMP400C', 1299, 575, 'SMPS', 'Artis', 'placeholder_image.jpg', 'ARTIS-SMP400C', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Artis SMP 400R SMPS', '<p>The Artis SMP 400R SMPS is a reliable 400W power supply unit for budget PC builds, featuring enhanced cooling and protection features for stable power delivery.</p><p><strong>Key Features:</strong></p><ul><li>400W power output</li><li>120mm cooling fan</li><li>Overload and short-circuit protection</li><li>ATX form factor</li><li>Multiple power connectors</li><li>Energy-efficient design</li></ul><p></p>', 'SMPS', 'ARTIS-SMP400R', 1199, 650, 'SMPS', 'Artis', 'placeholder_image.jpg', 'ARTIS-SMP400R', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2MP IR Dome Camera CP-UNC-DA21PL3-Y', '<p>CP PLUS 2MP IR Dome Camera offers high-definition indoor surveillance with reliable infrared night vision. Designed for offices, retail, and homes, it supports multiple video formats and provides clear footage with robust performance.</p><p><strong>Key Features:</strong></p><ul><li>2MP resolution for sharp video</li><li>IR night vision up to 30m</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for dust and water resistance</li><li>3.6mm fixed lens for wide coverage</li><li>Built-in microphone for audio recording</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-DA21PL3-Y', 4150, 1675, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-DA21PL3-Y', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2MP IR Dome Camera with Audio CP-UNC-DA21PL3C', '<p>CP PLUS 2MP IR Dome Camera with built-in microphone delivers high-definition indoor surveillance. Featuring infrared night vision and support for multiple video formats, it''s ideal for offices, retail, and residential applications.</p><p><strong>Key Features:</strong></p><ul><li>2MP resolution for clear video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for durability</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-DA21PL3C', 4550, 1575, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-DA21PL3C', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2MP IR Dome Camera with Audio CP-UNC-DA21PL3C-L-Y', '<p>CP PLUS 2MP IR Dome Camera with built-in microphone and enhanced IR range provides high-definition indoor surveillance. With support for multiple video formats and reliable night vision, it''s suitable for offices, retail, and homes.</p><p><strong>Key Features:</strong></p><ul><li>2MP resolution for sharp video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for durability</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-DA21PL3C-L-Y', 4800, 1800, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-DA21PL3C-L-Y', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4MP IR Dome Camera CP-UNC-DA41PL3-Y', '<p>CP PLUS 4MP IR Dome Camera delivers high-definition indoor surveillance with enhanced infrared night vision. Ideal for offices, retail, and larger homes, it supports multiple video formats and ensures clear footage in various lighting conditions.</p><p><strong>Key Features:</strong></p><ul><li>4MP resolution for detailed video</li><li>IR night vision up to 30m</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for dust and water resistance</li><li>3.6mm fixed lens for wide coverage</li><li>Robust design for reliable performance</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-DA41PL3-Y', 5800, 1900, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-DA41PL3-Y', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4MP IR Dome Camera with Audio CP-UNC-DA41L3C-L', '<p>CP PLUS 4MP IR Dome Camera with built-in microphone offers high-definition indoor surveillance with enhanced night vision. Supporting multiple video formats, it''s ideal for offices, retail, and larger residential setups.</p><p><strong>Key Features:</strong></p><ul><li>4MP resolution for clear video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for durability</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-DA41L3C-L', 6400, 2700, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-DA41L3C-L', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 5MP IR Dome Camera with Audio CP-UNC-DA51L3C', '<p>CP PLUS 5MP IR Dome Camera with built-in microphone provides high-definition indoor surveillance with superior night vision. Supporting multiple video formats, it''s ideal for offices, retail, and large residential applications.</p><p><strong>Key Features:</strong></p><ul><li>5MP resolution for detailed video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for dust and water resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-DA51L3C', 6900, 3500, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-DA51L3C', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2.4MP Dual Light Bullet Camera CP-URC-TC24PL3', '<p>CP PLUS 2.4MP Dual Light Bullet Camera offers high-definition outdoor surveillance with dual light technology (IR and warm light) for enhanced night vision. Ideal for homes, offices, and commercial spaces, it supports multiple video formats and delivers clear footage.</p><p><strong>Key Features:</strong></p><ul><li>2.4MP resolution for clear video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li><li>Robust design for outdoor use</li></ul><p></p>', 'CCTV Camera', 'CP-URC-TC24PL3', 2800, 725, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-URC-TC24PL3', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2.4MP Dual Light Bullet Camera CP-URC-TC24PL2-V3', '<p>CP PLUS 2.4MP Dual Light Bullet Camera provides high-definition outdoor surveillance with dual light technology (IR and warm light) for enhanced night vision. Suitable for homes, offices, and commercial spaces, it supports multiple video formats for seamless integration.</p><p><strong>Key Features:</strong></p><ul><li>2.4MP resolution for clear video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li><li>Robust design for outdoor durability</li></ul><p></p>', 'CCTV Camera', 'CP-URC-TC24PL2-V3', 2650, 725, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-URC-TC24PL2-V3', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2.4MP Dual Light Bullet Camera with Audio CP-URC-TC24PL2C-V3', '<p>CP PLUS 2.4MP Dual Light Bullet Camera with built-in microphone delivers high-definition outdoor surveillance. Featuring dual light technology (IR and warm light), it ensures clear footage in low-light conditions. Ideal for homes, offices, and commercial spaces, it supports multiple video formats for seamless integration.</p><p><strong>Key Features:</strong></p><ul><li>2.4MP resolution for sharp video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-URC-TC24PL2C-V3', 2950, 800, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-URC-TC24PL2C-V3', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 5MP Dual Light Bullet Camera CP-USC-TC51PL2-V5', '<p>CP PLUS 5MP Dual Light Bullet Camera offers high-definition outdoor surveillance with advanced dual light technology (IR and warm light) for superior night vision. Ideal for commercial spaces, homes, and offices, it supports multiple video formats and ensures clear footage in various lighting conditions.</p><p><strong>Key Features:</strong></p><ul><li>5MP resolution for detailed video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li><li>Robust design for outdoor durability</li></ul><p></p>', 'CCTV Camera', 'CP-USC-TC51PL2-V5', 3500, 1050, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-USC-TC51PL2-V5', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 5MP Dual Light Bullet Camera with Audio CP-URC-TC51PL3C', '<p>CP PLUS 5MP Dual Light Bullet Camera with built-in microphone delivers high-definition outdoor surveillance. Featuring dual light technology (IR and warm light), it ensures clear footage in low-light conditions. Ideal for homes, offices, and commercial spaces, it supports multiple video formats.</p><p><strong>Key Features:</strong></p><ul><li>5MP resolution for high-quality video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-URC-TC51PL3C', 3900, 1100, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-URC-TC51PL3C', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 5MP Dual Light Bullet Camera with Audio CP-GPC-TC51PL3C-L-V2', '<p>CP PLUS 5MP Dual Light Bullet Camera with built-in microphone offers high-definition outdoor surveillance. Equipped with dual light technology (IR and warm light), it provides superior night vision and clear footage in low-light conditions. Ideal for commercial spaces, homes, and offices.</p><p><strong>Key Features:</strong></p><ul><li>5MP resolution for high-quality video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-GPC-TC51PL3C-L-V2', 4500, 1375, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-GPC-TC51PL3C-L-V2', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2.4MP Dual Light Bullet Camera with Audio CP-GPC-TA24PL2C-SE', '<p>CP PLUS 2.4MP Dual Light Bullet Camera with built-in microphone delivers high-definition outdoor surveillance. Featuring dual light technology (IR and warm light), it ensures clear footage in low-light conditions. Ideal for homes, offices, and commercial spaces, it supports multiple video formats for seamless integration.</p><p><strong>Key Features:</strong></p><ul><li>2.4MP resolution for sharp video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-GPC-TA24PL2C-SE', 3400, 150, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-GPC-TA24PL2C-SE', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2MP IR Bullet Camera CP-UNC-TA21PL3-Y', '<p>CP PLUS 2MP IR Bullet Camera offers high-definition outdoor surveillance with reliable infrared night vision. Designed for homes, offices, and commercial spaces, it supports multiple video formats and provides clear footage with robust performance.</p><p><strong>Key Features:</strong></p><ul><li>2MP resolution for sharp video</li><li>IR night vision up to 30m</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li><li>Built-in microphone for audio recording</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-TA21PL3-Y', 4250, 1650, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-TA21PL3-Y', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2MP IR Bullet Camera with Audio CP-UNC-TA21PL3C', '<p>CP PLUS 2MP IR Bullet Camera with built-in microphone delivers high-definition outdoor surveillance. Featuring infrared night vision and support for multiple video formats, it''s ideal for homes, offices, and commercial spaces.</p><p><strong>Key Features:</strong></p><ul><li>2MP resolution for clear video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-TA21PL3C', 4750, 1900, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-TA21PL3C', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2MP IR Bullet Camera with Audio CP-UNC-TA21PL3C-L-Y', '<p>CP PLUS 2MP IR Bullet Camera with built-in microphone and enhanced IR range provides high-definition outdoor surveillance. With support for multiple video formats and reliable night vision, it''s suitable for homes, offices, and commercial spaces.</p><p><strong>Key Features:</strong></p><ul><li>2MP resolution for sharp video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-TA21PL3C-L-Y', 5100, 2200, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-TA21PL3C-L-Y', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4MP IR Bullet Camera with Audio CP-UNC-TA41PL3C-Y', '<p>CP PLUS 4MP IR Bullet Camera with built-in microphone delivers high-definition outdoor surveillance with enhanced infrared night vision. Supporting multiple video formats, it''s ideal for offices, retail, and larger residential setups.</p><p><strong>Key Features:</strong></p><ul><li>4MP resolution for clear video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-TA41PL3C-Y', 6100, 2450, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-TA41PL3C-Y', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4MP IR Bullet Camera with Audio CP-UNC-TA41PL3C-L-Y', '<p>CP PLUS 4MP IR Bullet Camera with built-in microphone and enhanced IR range provides high-definition outdoor surveillance. Supporting multiple video formats, it''s ideal for offices, retail, and larger residential setups.</p><p><strong>Key Features:</strong></p><ul><li>4MP resolution for clear video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-TA41PL3C-L-Y', 6700, 2500, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-TA41PL3C-L-Y', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 5MP IR Bullet Camera with Audio CP-UNC-TA51L3C', '<p>CP PLUS 5MP IR Bullet Camera with built-in microphone provides high-definition outdoor surveillance with superior night vision. Supporting multiple video formats, it''s ideal for offices, retail, and large residential applications.</p><p><strong>Key Features:</strong></p><ul><li>5MP resolution for detailed video</li><li>IR night vision up to 30m</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for weather resistance</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-UNC-TA51L3C', 7200, 3950, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-UNC-TA51L3C', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 5A SMPS for CCTV Systems CP-DPS-5A', '<p>CP PLUS 5A SMPS is a reliable power supply unit designed for CCTV systems, ensuring stable and efficient power delivery to cameras and recorders. Compact and durable, it''s ideal for small to medium-sized surveillance setups.</p><p><strong>Key Features:</strong></p><ul><li>5A output for multiple CCTV devices</li><li>Stable 12V DC output</li><li>Overload and short-circuit protection</li><li>Compact design for easy installation</li><li>High efficiency with low heat generation</li><li>Suitable for indoor use</li></ul><p></p>', 'SMPS', 'CP-DPS-5A', 1450, 340, 'SMPS', 'CP PLUS', 'placeholder_image.jpg', 'CP-DPS-5A', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 10A SMPS for CCTV Systems CP-DPS-10A', '<p>CP PLUS 10A SMPS is a high-capacity power supply unit designed for CCTV systems, providing stable and efficient power delivery to multiple cameras and recorders. Compact and durable, it''s ideal for medium to large surveillance setups.</p><p><strong>Key Features:</strong></p><ul><li>10A output for high-power CCTV systems</li><li>Stable 12V DC output</li><li>Overload and short-circuit protection</li><li>Compact design for easy installation</li><li>High efficiency with low heat generation</li><li>Suitable for indoor use</li></ul><p></p>', 'SMPS', 'CP-DPS-10A', 2400, 470, 'SMPS', 'CP PLUS', 'placeholder_image.jpg', 'CP-DPS-10A', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Secureye 5A SMPS for CCTV Systems S-PS-5A', '<p>Secureye 5A SMPS is a reliable power supply unit designed for CCTV systems, ensuring stable power delivery to cameras and recorders. Compact and efficient, it''s ideal for small to medium-sized surveillance setups.</p><p><strong>Key Features:</strong></p><ul><li>5A output for multiple CCTV devices</li><li>Stable 12V DC output</li><li>Overload and short-circuit protection</li><li>Compact design for easy installation</li><li>High efficiency with low heat generation</li><li>Suitable for indoor use</li></ul><p></p>', 'SMPS', 'S-PS-5A', 1250, 400, 'SMPS', 'Secureye', 'placeholder_image.jpg', 'S-PS-5A', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Secureye 10A SMPS for CCTV Systems S-PS-10A', '<p>Secureye 10A SMPS is a high-capacity power supply unit designed for CCTV systems, providing stable power to multiple cameras and recorders. Durable and efficient, it''s suitable for medium to large surveillance setups.</p><p><strong>Key Features:</strong></p><ul><li>10A output for high-power CCTV systems</li><li>Stable 12V DC output</li><li>Overload and short-circuit protection</li><li>Compact design for easy installation</li><li>High efficiency with low heat generation</li><li>Suitable for indoor use</li></ul><p></p>', 'SMPS', 'S-PS-10A', 2100, 450, 'SMPS', 'Secureye', 'placeholder_image.jpg', 'S-PS-10A', '8504', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Seagate Surveillance HDD 500GB ST500VX000', '<p>Seagate Surveillance HDD 500GB is optimized for DVR and NVR systems, offering reliable storage for continuous video recording. Designed for 24/7 operation, it ensures high performance and durability for small-scale CCTV setups.</p><p><strong>Key Features:</strong></p><ul><li>500GB capacity for video storage</li><li>Optimized for 24/7 surveillance workloads</li><li>Supports up to 32 cameras</li><li>High reliability with low power consumption</li><li>3.5-inch form factor</li><li>Advanced error recovery for uninterrupted recording</li></ul><p></p>', 'Storage', 'ST500VX000', 3200, 1050, 'Storage', 'Seagate', 'placeholder_image.jpg', 'ST500VX000', '8471', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Seagate Surveillance HDD 1TB ST1000VX005', '<p>Seagate Surveillance HDD 1TB is designed for DVR and NVR systems, providing reliable storage for continuous video recording. Optimized for 24/7 operation, it''s ideal for medium-scale CCTV setups with high performance and durability.</p><p><strong>Key Features:</strong></p><ul><li>1TB capacity for extended video storage</li><li>Optimized for 24/7 surveillance workloads</li><li>Supports up to 64 cameras</li><li>High reliability with low power consumption</li><li>3.5-inch form factor</li><li>Advanced error recovery for uninterrupted recording</li></ul><p></p>', 'Storage', 'ST1000VX005', 5999, 3350, 'Storage', 'Seagate', 'placeholder_image.jpg', 'ST1000VX005', '8471', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Seagate Surveillance HDD 2TB ST2000VX008', '<p>Seagate Surveillance HDD 2TB is engineered for DVR and NVR systems, offering robust storage for continuous video recording. Optimized for 24/7 operation, it''s ideal for medium to large-scale CCTV setups with high reliability.</p><p><strong>Key Features:</strong></p><ul><li>2TB capacity for extended video storage</li><li>Optimized for 24/7 surveillance workloads</li><li>Supports up to 64 cameras</li><li>High reliability with low power consumption</li><li>3.5-inch form factor</li><li>Advanced error recovery for uninterrupted recording</li></ul><p></p>', 'Storage', 'ST2000VX008', 6800, 4225, 'Storage', 'Seagate', 'placeholder_image.jpg', 'ST2000VX008', '8471', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Seagate Surveillance HDD 4TB ST4000VX013', '<p>Seagate Surveillance HDD 4TB is designed for high-capacity DVR and NVR systems, providing reliable storage for continuous video recording. Optimized for 24/7 operation, it''s ideal for large-scale CCTV setups with enhanced durability.</p><p><strong>Key Features:</strong></p><ul><li>4TB capacity for extensive video storage</li><li>Optimized for 24/7 surveillance workloads</li><li>Supports up to 64 cameras</li><li>High reliability with low power consumption</li><li>3.5-inch form factor</li><li>Advanced error recovery for uninterrupted recording</li></ul><p></p>', 'Storage', 'ST4000VX013', 13000, 6950, 'Storage', 'Seagate', 'placeholder_image.jpg', 'ST4000VX013', '8471', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Seagate Surveillance HDD 6TB ST6000VX001', '<p>Seagate Surveillance HDD 6TB is built for high-capacity DVR and NVR systems, offering robust storage for continuous video recording. Optimized for 24/7 operation, it''s ideal for large-scale CCTV setups with superior reliability.</p><p><strong>Key Features:</strong></p><ul><li>6TB capacity for extensive video storage</li><li>Optimized for 24/7 surveillance workloads</li><li>Supports up to 64 cameras</li><li>High reliability with low power consumption</li><li>3.5-inch form factor</li><li>Advanced error recovery for uninterrupted recording</li></ul><p></p>', 'Storage', 'ST6000VX001', 21000, 11100, 'Storage', 'Seagate', 'placeholder_image.jpg', 'ST6000VX001', '8471', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Seagate Surveillance HDD 8TB ST8000VX004', '<p>Seagate Surveillance HDD 8TB is engineered for high-capacity DVR and NVR systems, providing extensive storage for continuous video recording. Optimized for 24/7 operation, it''s ideal for large-scale CCTV setups with enhanced durability and performance.</p><p><strong>Key Features:</strong></p><ul><li>8TB capacity for vast video storage</li><li>Optimized for 24/7 surveillance workloads</li><li>Supports up to 64 cameras</li><li>High reliability with low power consumption</li><li>3.5-inch form factor</li><li>Advanced error recovery for uninterrupted recording</li></ul><p></p>', 'Storage', 'ST8000VX004', 25999, 15950, 'Storage', 'Seagate', 'placeholder_image.jpg', 'ST8000VX004', '8471', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 90m Coaxial Cable CP-PCC-90', '<p>CP PLUS 90m Coaxial Cable is designed for CCTV systems, providing reliable and stable transmission of video signals. Made from high-quality materials, it ensures minimal signal loss and durability for long-distance connections.</p><p><strong>Key Features:</strong></p><ul><li>90m length for extended CCTV installations</li><li>High-quality coaxial cable for minimal signal loss</li><li>Supports HD video transmission</li><li>Durable and weather-resistant design</li><li>Compatible with CVI/TVI/AHD/CVBS cameras</li><li>Easy to install with standard connectors</li></ul><p></p>', 'Cables', 'CP-PCC-90', 1550, 800, 'Cables', 'CP PLUS', 'placeholder_image.jpg', 'CP-PCC-90', '8544', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 180m Coaxial Cable CP-PCC-180', '<p>CP PLUS 180m Coaxial Cable is designed for CCTV systems, ensuring reliable and stable transmission of video signals over long distances. Constructed with high-quality materials, it minimizes signal loss and is built for durability, making it ideal for extensive surveillance setups.</p><p><strong>Key Features:</strong></p><ul><li>180m length for large-scale CCTV installations</li><li>High-quality coaxial cable for minimal signal loss</li><li>Supports HD video transmission</li><li>Durable and weather-resistant design</li><li>Compatible with CVI/TVI/AHD/CVBS cameras</li><li>Easy to install with standard connectors</li></ul><p></p>', 'Cables', 'CP-PCC-180', 2800, 1400, 'Cables', 'CP PLUS', 'placeholder_image.jpg', 'CP-PCC-180', '8544', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4 Channel PoE Switch CP-SAVW-HPU4H2-65', '<p>CP PLUS 4 Channel PoE Switch is designed to power and connect IP cameras in CCTV systems, offering reliable network performance. With Power over Ethernet (PoE) support, it simplifies installation by reducing cabling needs, ideal for small to medium surveillance setups.</p><p><strong>Key Features:</strong></p><ul><li>4 PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 65W total PoE power budget</li><li>2 uplink ports for network expansion</li><li>Plug-and-play installation</li><li>Compact design for easy deployment</li></ul><p></p>', 'Network Switch', 'CP-SAVW-HPU4H2-65', 3200, 900, 'Network Switch', 'CP PLUS', 'placeholder_image.jpg', 'CP-SAVW-HPU4H2-65', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4 Port Gigabit PoE Switch CP-GPU4G2-48', '<p>CP PLUS 4 Port Gigabit PoE Switch provides high-speed network connectivity and power for IP cameras in CCTV systems. With gigabit ports and a robust PoE power budget, it''s ideal for medium-scale surveillance networks requiring high-bandwidth performance.</p><p><strong>Key Features:</strong></p><ul><li>4 Gigabit PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 48W total PoE power budget</li><li>2 uplink ports for network expansion</li><li>High-speed gigabit connectivity</li><li>Plug-and-play installation</li></ul><p></p>', 'Network Switch', 'CP-GPU4G2-48', 4300, 1850, 'Network Switch', 'CP PLUS', 'placeholder_image.jpg', 'CP-GPU4G2-48', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 8 Channel PoE Switch CP-HPU8H2-96-V2', '<p>CP PLUS 8 Channel PoE Switch is designed for powering and connecting IP cameras in CCTV systems, offering reliable network performance for medium to large surveillance setups. With a high PoE power budget, it simplifies installation and supports robust connectivity.</p><p><strong>Key Features:</strong></p><ul><li>8 PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 96W total PoE power budget</li><li>2 uplink ports for network expansion</li><li>Plug-and-play installation</li><li>Durable design for reliable performance</li></ul><p></p>', 'Network Switch', 'CP-HPU8H2-96-V2', 5800, 1350, 'Network Switch', 'CP PLUS', 'placeholder_image.jpg', 'CP-HPU8H2-96-V2', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 8 Port Gigabit PoE Switch CP-GPU8G2-96', '<p>CP PLUS 8 Port Gigabit PoE Switch provides high-speed network connectivity and power for IP cameras in CCTV systems. With gigabit ports and a high PoE power budget, it''s ideal for large-scale surveillance networks requiring high-bandwidth performance.</p><p><strong>Key Features:</strong></p><ul><li>8 Gigabit PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 96W total PoE power budget</li><li>2 uplink ports for network expansion</li><li>High-speed gigabit connectivity</li><li>Plug-and-play installation</li></ul><p></p>', 'Network Switch', 'CP-GPU8G2-96', 6500, 2600, 'Network Switch', 'CP PLUS', 'placeholder_image.jpg', 'CP-GPU8G2-96', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 16 Port PoE Switch CP-HPU16G2F1-20', '<p>CP PLUS 16 Port PoE Switch is designed for large-scale CCTV systems, providing power and connectivity for multiple IP cameras. With a high PoE power budget and robust network performance, it''s ideal for extensive surveillance networks.</p><p><strong>Key Features:</strong></p><ul><li>16 PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 200W total PoE power budget</li><li>1 uplink port for network expansion</li><li>Plug-and-play installation</li><li>High reliability for continuous operation</li></ul><p></p>', 'Network Switch', 'CP-HPU16G2F1-20', 11000, 5750, 'Network Switch', 'CP PLUS', 'placeholder_image.jpg', 'CP-HPU16G2F1-20', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Secureye 4 Port PoE Switch S-4FE-2UE-LD-NB', '<p>Secureye 4 Port PoE Switch is designed to power and connect IP cameras in CCTV systems, offering reliable network performance for small surveillance setups. With Power over Ethernet (PoE) support, it simplifies installation and ensures stable connectivity.</p><p><strong>Key Features:</strong></p><ul><li>4 PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 60W total PoE power budget</li><li>2 uplink ports for network expansion</li><li>Plug-and-play installation</li><li>Compact and durable design</li></ul><p></p>', 'Network Switch', 'S-4FE-2UE-LD-NB', 3500, 800, 'Network Switch', 'Secureye', 'placeholder_image.jpg', 'S-4FE-2UE-LD-NB', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Secureye 8 Port PoE Switch S-8FE-2UE-LD-NB', '<p>Secureye 8 Port PoE Switch provides power and connectivity for IP cameras in CCTV systems, offering reliable performance for medium-scale surveillance setups. With PoE support, it simplifies installation and ensures stable network connectivity.</p><p><strong>Key Features:</strong></p><ul><li>8 PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 96W total PoE power budget</li><li>2 uplink ports for network expansion</li><li>Plug-and-play installation</li><li>Durable design for continuous operation</li></ul><p></p>', 'Network Switch', 'S-8FE-2UE-LD-NB', 5200, 1100, 'Network Switch', 'Secureye', 'placeholder_image.jpg', 'S-8FE-2UE-LD-NB', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('Secureye 8 Port Gigabit PoE Switch SSP-8GE-2UG-NB', '<p>Secureye 8 Port Gigabit PoE Switch delivers high-speed network connectivity and power for IP cameras in CCTV systems. With gigabit ports and a robust PoE power budget, it''s ideal for large-scale surveillance networks requiring high-bandwidth performance.</p><p><strong>Key Features:</strong></p><ul><li>8 Gigabit PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 120W total PoE power budget</li><li>2 uplink ports for network expansion</li><li>High-speed gigabit connectivity</li><li>Plug-and-play installation</li></ul><p></p>', 'Network Switch', 'SSP-8GE-2UG-NB', 6800, 2350, 'Network Switch', 'Secureye', 'placeholder_image.jpg', 'SSP-8GE-2UG-NB', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('TP-Link 8-Port 10/100Mbps PoE Switch TL-SL1311P', '<p>TP-Link TL-SL1311P is an 8-port 10/100Mbps PoE switch designed for small to medium-sized CCTV systems, providing power and connectivity for IP cameras. With PoE support, it simplifies installation and ensures stable network performance.</p><p><strong>Key Features:</strong></p><ul><li>8 PoE ports (10/100Mbps) for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 65W total PoE power budget</li><li>3 uplink ports (2 10/100Mbps, 1 Gigabit)</li><li>Plug-and-play installation</li><li>Extend mode for up to 250m transmission</li></ul><p></p>', 'Network Switch', 'TL-SL1311P', 6500, 2875, 'Network Switch', 'TP-Link', 'placeholder_image.jpg', 'TL-SL1311P', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('TP-Link 16-Port Gigabit PoE Switch TL-SG1218MPE', '<p>TP-Link TL-SG1218MPE is a 16-port Gigabit PoE switch designed for large-scale CCTV systems, offering high-speed connectivity and power for IP cameras. With a robust PoE power budget, it''s ideal for extensive surveillance networks.</p><p><strong>Key Features:</strong></p><ul><li>16 Gigabit PoE ports for IP cameras</li><li>Supports IEEE 802.3af/at PoE standards</li><li>Up to 192W total PoE power budget</li><li>2 Gigabit uplink ports + 2 SFP slots</li><li>Advanced management features (VLAN, QoS)</li><li>Rack-mountable design</li></ul><p></p>', 'Network Switch', 'TL-SG1218MPE', 15500, 9650, 'Network Switch', 'TP-Link', 'placeholder_image.jpg', 'TL-SG1218MPE', '8517', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2MP Wi-Fi Smart Security Camera EZ-P21', '<p>CP PLUS EZ-P21 2MP Wi-Fi Smart Security Camera offers full HD indoor surveillance with 360? pan and tilt functionality. Ideal for homes and small offices, it provides clear footage, night vision, and remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>2MP resolution for full HD video</li><li>360? pan and tilt for complete coverage</li><li>IR night vision up to 20m</li><li>Two-way talk for communication</li><li>Supports SD card up to 256GB</li><li>Wi-Fi connectivity with Alexa/Google support</li></ul><p></p>', 'Camera', 'EZ-P21', 3100, 1500, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'EZ-P21', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 3MP Wi-Fi PT Camera CP-E38A', '<p>CP PLUS CP-E38A 3MP Wi-Fi PT Camera provides high-definition indoor surveillance with 360? pan and tilt functionality. Ideal for homes and offices, it offers full-color night vision, two-way talk, and remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>3MP resolution for sharp video</li><li>360? pan and tilt for complete coverage</li><li>Full-color night vision up to 15m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>Wi-Fi connectivity with Alexa/Google support</li></ul><p></p>', 'Camera', 'CP-E38A', 4950, 1250, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-E38A', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4MP Wi-Fi PT Camera CP-E48A', '<p>CP PLUS CP-E48A 4MP Wi-Fi PT Camera offers high-definition indoor surveillance with 360? pan and tilt functionality. Ideal for homes and offices, it provides full-color night vision, two-way talk, and remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>4MP resolution for detailed video</li><li>360? pan and tilt for complete coverage</li><li>Full-color night vision up to 15m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>Wi-Fi connectivity with Alexa/Google support</li></ul><p></p>', 'Camera', 'CP-E48A', 5200, 1550, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-E48A', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 3MP Wi-Fi PT Camera CP-T31A', '<p>CP PLUS CP-T31A 3MP Wi-Fi PT Camera provides high-definition indoor surveillance with 360? pan and tilt functionality. Ideal for homes and small offices, it offers full HD video, night vision, and remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>3MP resolution for sharp video</li><li>360? pan and tilt for complete coverage</li><li>IR night vision up to 15m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>Wi-Fi connectivity with Alexa/Google support</li></ul><p></p>', 'Camera', 'CP-T31A', 4999, 1600, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-T31A', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 8MP Wi-Fi PT Camera CP-E81AR', '<p>CP PLUS CP-E81AR 8MP Wi-Fi PT Camera offers ultra-high-definition indoor surveillance with 360? pan and tilt functionality. Ideal for homes and offices, it provides full-color night vision, two-way talk, and remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>8MP resolution for ultra-clear video</li><li>360? pan and tilt for complete coverage</li><li>Full-color night vision up to 15m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>Wi-Fi connectivity with Alexa/Google support</li></ul><p></p>', 'Camera', 'CP-E81AR', 6999, 2700, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-E81AR', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 3MP 4G PT Camera R33G', '<p>CP PLUS R33G 3MP 4G PT Camera offers high-definition outdoor surveillance with 360? pan and tilt functionality. Designed for areas without Wi-Fi, it uses 4G connectivity for remote access via the EzyKam+ app, ideal for remote locations.</p><p><strong>Key Features:</strong></p><ul><li>3MP resolution for sharp video</li><li>360? pan and tilt for complete coverage</li><li>IR night vision up to 20m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>4G SIM support for remote connectivity</li></ul><p></p>', 'Camera', 'R33G', 5600, 1850, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'R33G', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 3MP 4G PT Camera CP-V33GN', '<p>CP PLUS CP-V33GN 3MP 4G PT Camera provides high-definition outdoor surveillance with 360? pan and tilt functionality. Using 4G connectivity, it''s ideal for remote locations without Wi-Fi, offering remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>3MP resolution for sharp video</li><li>360? pan and tilt for complete coverage</li><li>IR night vision up to 20m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>4G SIM support for remote connectivity</li></ul><p></p>', 'Camera', 'CP-V33GN', 4999, 1900, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-V33GN', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4MP Wi-Fi Full Color PT Camera CP-Z43A', '<p>CP PLUS CP-Z43A 4MP Wi-Fi PT Camera offers high-definition outdoor surveillance with 360? pan and tilt functionality. Featuring full-color night vision, it''s ideal for homes and offices, with remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>4MP resolution for detailed video</li><li>360? pan and tilt for complete coverage</li><li>Full-color night vision up to 10m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>Wi-Fi connectivity with Alexa/Google support</li></ul><p></p>', 'Camera', 'CP-Z43A', 8000, 2500, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-Z43A', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 3MP 4G PT Camera EZ-S31G', '<p>CP PLUS EZ-S31G 3MP 4G PT Camera provides high-definition outdoor surveillance with 360? pan and tilt functionality. Using 4G connectivity, it''s ideal for remote locations without Wi-Fi, offering remote access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>3MP resolution for sharp video</li><li>360? pan and tilt for complete coverage</li><li>IR night vision up to 20m</li><li>Two-way talk for communication</li><li>Supports SD card up to 256GB</li><li>4G SIM support for remote connectivity</li></ul><p></p>', 'Camera', 'EZ-S31G', 9890, 2250, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'EZ-S31G', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 3MP 4G Pan/Tilt Camera CP-Z32G', '<p>CP PLUS CP-Z32G 3MP 4G Pan/Tilt Camera offers high-definition outdoor surveillance with 360? pan and tilt functionality. Designed for remote areas without Wi-Fi, it uses 4G connectivity for access via the EzyKam+ app, ideal for homes and businesses.</p><p><strong>Key Features:</strong></p><ul><li>3MP resolution for sharp video</li><li>360? pan and tilt for complete coverage</li><li>IR night vision up to 20m</li><li>Two-way talk for communication</li><li>Supports SD card up to 128GB</li><li>4G SIM support for remote connectivity</li></ul><p></p>', 'Camera', 'CP-Z32G', 8100, 2800, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-Z32G', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 4MP Solar-Powered 4G PT Camera CP-Z44R', '<p>CP PLUS CP-Z44R 4MP Solar-Powered 4G PT Camera offers high-definition outdoor surveillance with 360? pan and tilt functionality. Solar-powered and using 4G connectivity, it''s ideal for remote locations without power or Wi-Fi, with access via the EzyKam+ app.</p><p><strong>Key Features:</strong></p><ul><li>4MP resolution for detailed video</li><li>360? pan and tilt for complete coverage</li><li>Full-color night vision up to 10m</li><li>Solar-powered with battery backup</li><li>Supports SD card up to 128GB</li><li>4G SIM support for remote connectivity</li></ul><p></p>', 'Camera', 'CP-Z44R', 12600, 4450, 'Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-Z44R', '852580', 18, 'active');

INSERT INTO products (title, description, product_type, model_number, mrp, price, category, brand, image, handle, hsn_code, gst_rate, status) VALUES
('CP PLUS 2.4MP Dual Light Dome Camera with Audio CP-URC-DC24PL3C', '<p>CP PLUS 2.4MP Dual Light Dome Camera with built-in microphone delivers high-definition indoor surveillance. Featuring dual light technology (IR and warm light), it ensures clear footage in various lighting conditions. With support for multiple video formats, it''s ideal for offices, shops, and homes.</p><p><strong>Key Features:</strong></p><ul><li>2.4MP resolution for sharp video</li><li>Dual light night vision (IR up to 30m, warm light up to 20m)</li><li>Built-in microphone for audio recording</li><li>Supports CVI/TVI/AHD/CVBS formats</li><li>IP67 rating for durability</li><li>3.6mm fixed lens for wide coverage</li></ul><p></p>', 'CCTV Camera', 'CP-URC-DC24PL3C', 3100, 1500, 'CCTV Camera', 'CP PLUS', 'placeholder_image.jpg', 'CP-URC-DC24PL3C', '852580', 18, 'active');